
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
<<<<<<< HEAD
    password: Chathu@2000
=======
    password: tnbr20011
>>>>>>> d4964be41ceb321ff53453a233a7d5f917748552
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
